import { mkdirSync, cpSync, writeFileSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const result = spawnSync(process.execPath, [path.join(root, 'scripts/check-project.mjs'), '--json'], { encoding: 'utf8' });
const report = JSON.parse(result.stdout);
const protectedOwners = new Set(['オメガイヤーカフα','オメガスーツα','オメガアームα','オメガアクセサリーα','オメガレッグα']);
const unexpected = report.errors.filter(e => !(e.kind === 'unknown-skill' && e.name === 'オメガレゾナンス' && protectedOwners.has(e.owner)));
if (unexpected.length || report.warnings.length) throw new Error(JSON.stringify({unexpected,warnings:report.warnings}));
console.log(`Structural check: ${report.errors.length} preserved Omega references; no other errors or warnings.`);
const dest = path.join(root, 'dist');
if (existsSync(dest)) throw new Error('dist already exists; use a clean build directory.');
mkdirSync(dest);
for (const file of ['index.html','asst.html','builder.html','damage_talisman.html','talisman.html','database.html']) cpSync(path.join(root,file),path.join(dest,file));
for (const dir of ['css','assets','js']) cpSync(path.join(root,dir),path.join(dest,dir),{recursive:true,filter: source => !/\.bak$|asst_backup\.js$|\.mjs$/.test(source)});
writeFileSync(path.join(dest,'.nojekyll'),'');
writeFileSync(path.join(dest,'version.json'),JSON.stringify({commit:process.env.GITHUB_SHA || 'local-preview',builtAt:new Date().toISOString()}));
console.log('Packaged six pages and runtime assets; research and extraction data excluded.');
